application: oscar-parklife
version: 4
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /images
  static_dir: public/images
- url: /tasks/.*
  script: tasks.py
- url: /admin/settings
  script: settings.py  
  login: admin
- url: /admin/blog
  script: blog.py  
  login: admin
- url: /admin/maintenance
  script: settings.py
  login: admin    
- url: /admin/maintenance/(.*)
  script: settings.py
  login: admin  
- url: /admin/edit/.*
  script: blog.py
  login: admin
- url: /service/entry/.*
  script: blog.py
  login: admin  
- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin  
- url: .*
  script: main.py

builtins:
- remote_api: on

derived_file_type:
- python_precompiled
