application: oscar-parklife
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /images
  static_dir: public/images
- url: /tasks/.*
  script: tasks.application
- url: /admin/settings
  script: settings.application  
  login: admin
- url: /admin/blog
  script: blog.application
  login: admin
- url: /admin/maintenance
  script: settings.application
  login: admin    
- url: /admin/maintenance/(.*)
  script: settings.application
  login: admin  
- url: /admin/edit/.*
  script: blog.application
  login: admin
- url: /service/entry/.*
  script: blog.application
  login: admin  
- url: .*
  script: main.application

derived_file_type:
- python_precompiled

builtins:
- datastore_admin: on

libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "1.2"